apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-deploy
  template:
    metadata:
      labels:
        app: orchestrator-deploy
    spec:
      containers:
        - name: orchestrator-container
          image: orchestrator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 1234
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: queue_length_check_interval
              value: "1000"
            - name: task_check_interval
              value: "1000"
---

apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  labels:
    app: orchestrator-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orchestrator-deploy

---

apiVersion: v1
kind: Service
metadata:
  name: orchestrator-metrics
  labels:
    app: orchestrator-deploy
spec:
  ports:
    - port: 1234
      targetPort: 1234
  selector:
    app: orchestrator-deploy